import { Types } from 'mongoose';
import { HospitalCategory, HospitalStatus, HospitalSpecialization, ApprovalStatus, City } from '../schemas/common.enums';

const seedHospitals = [

    {
        name: "حرستا الوطني",
        address: "حرستا موقف الانتاج",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["5329816"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.55580796430709,
        longitude: 36.363004370009634,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0,
    },
    {
        name: "القطيفة",
        address: "القطيفة",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["7755202"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.724927553818596,
        longitude: 36.58632875719984,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0,
    },
    {
        name: "مشفى التل الوطني",
        address: "التل الشارع الرئيسي",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["5919950"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.61637340602743,
        longitude: 36.3085159950839,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0,
    },
    
    {
        name: "مشفى أمية",
        address: "دمشق - الميسات",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["2776204", "2741181", "2762917"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.529286004865895,
        longitude: 36.29280663005931,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0,
    },
    {
        name: "مشفى الأمل",
        address: "دمشق - شارع بغداد أزبكية",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["4451335", "4451334", "4451321"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.52055957753476,
        longitude: 36.301034360044596,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0,
    },
    {
        name: "مشفى الأماني",
        address: "دمشق - مزرعة - شارع زكي الارسوزي",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["4454351", "4459685", "4451176"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.522573606908324,
        longitude: 36.29520623189591,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0,
    },
    {
        name: "مشفى الأهلي التخصصي",
        address: "دمشق - شارع فارس الخوري جانب جامع الحمزة و العباس",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["4465054", "4465058", "4465059"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.5258272866374,
        longitude: 36.318853250477346,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى القديس لويس",
        address: "دمشق - القصاع",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["4440460", "4440461", "4450705"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.51863661988217,
        longitude: 36.31612140478465,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "المركز الطبي الحديث ( هشام سنان )",
        address: "دمشق - ميسات شارع برنية",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["3310600", "7465"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.53293294899914,
        longitude: 36.29821566572238,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "ابن النفيس",
        address: "ركن الدين-تجمع ابن النفيس",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["5123637"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.54674680377432,
        longitude: 36.30696245053809,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى ابن رشد للأمراض النفسية",
        address: "كراجات العباسيين جانب مرآب وزارة الصحة",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["4418579", "4472109"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.53105375447168,
        longitude: 36.32380322506134,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "الزبداني",
        address: "الزبداني أول طلعة الجرجانية",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["7112991"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.712480494012866,
        longitude: 36.11294324164675,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "جيرود",
        address: "أول جيرود- دوار المشفى",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.PARTIALLY,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["7711900", "7711901"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.805144939132276,
        longitude: 36.73662242892427,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "داريا",
        address: "داريا جانب مدرسة التمريض",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.STOPPED,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: [], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.46266654912326,
        longitude: 36.22272136060918,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى قطنا الوطني",
        address: "قطنا",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["6893400"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.428168265397225,
        longitude: 36.0690660008959,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },

    {
        name: "مشفى دوما الإسعافي",
        address: "دوما-مقابل البلدية",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["5710570"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.57178441972244,
        longitude: 36.397199181716765,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "الرازي اعام",
        address: "حلب - المحافظة - شارع  سوق الانتاج",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.GENERAL,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["2260551", "2260482", "2283500"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 36.21119252914063,
        longitude: 37.14000973860258,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "زاهي ازرق",
        address: "حلب -الهلك",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.InternalMedicine,
        phones: [{ normal: ["4462544"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 36.23107842079532,
        longitude: 37.169149022325335,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى الأسدي",
        address: "دمشق - مزة جبل",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["6132501", "3326031"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.50017371628328,
        longitude: 36.23953960022237,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى الايطالي",
        address: "دمشق - طلياني",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["3326030", "3326031"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.52287282766072,
        longitude: 36.28977209985453,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى الأندلس التخصصي",
        address: "دمشق - تنظيم فيلات كفرسوسة",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["2114363", "2114635", "2117239"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.49572944931941,
        longitude: 36.28184841388162,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى بديع حمودة",
        address: "دمشق - شركسية روضة - شارع الملك بن مروان",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["3338523"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.519866146311806,
        longitude: 36.28600958648044,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى البشير",
        address: "دمشق - زاهرة غرب الفرن الالي",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["6318143", "6311166"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.46956258735983,
        longitude: 36.3302812498982,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى التوفيق",
        address: "دمشق - ابو رمانة -  شارع الأرجنتين",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["2228250", "2216364", "2229436"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.51498801746512,
        longitude: 36.2893921397549,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    },
    {
        name: "مشفى دار العيون و التجميل الجراحي",
        address: "دمشق - السبع بحرات - عين الكرش - دخلة السوق الحرة",
       cityName : City.Damascus,
        authAccountId: new Types.ObjectId(),
        category: HospitalCategory.PRIVATE,
        hospitalstatus: HospitalStatus.WORKS,
        hospitalSpecialization: HospitalSpecialization.GeneralMedicine,
        phones: [{ normal: ["2327281", "2327282"], clinic: [], whatsup: [], emergency: [] }],
        latitude: 33.51941450460495,
        longitude: 36.29699750969316,
        rating: 3,
        status: ApprovalStatus.APPROVED,
        subscriptionId: null,
        isSubscribed: false,
        searchCount: 0,
        profileViews: 0
    }
];

export default seedHospitals;
